openapi: 3.0.3
info:
  title: Frankfurter — FX Rates (ECB)
  version: "1.0.0"
  description: Free foreign exchange rates (ECB-sourced).
servers:
  - url: https://api.frankfurter.app
paths:
  /latest:
    get:
      operationId: fxLatest
      summary: Latest FX rates.
      parameters:
        - in: query
          name: from
          required: true
          schema: { type: string, example: "USD" }
        - in: query
          name: to
          required: true
          schema: { type: string, example: "EUR" }
        - in: query
          name: amount
          schema: { type: number, example: 1 }
      responses:
        "200":
          description: Latest rates JSON.
  /{date}:
    get:
      operationId: fxHistorical
      summary: Historical FX rates (YYYY-MM-DD).
      parameters:
        - in: path
          name: date
          required: true
          schema: { type: string, example: "2024-12-31" }
        - in: query
          name: from
          required: true
          schema: { type: string }
        - in: query
          name: to
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Historical rates JSON.
