openapi: 3.0.3
info:
  title: OpenCorporates — Company Search
  version: "1.0.0"
  description: Search global company registries.
servers:
  - url: https://api.opencorporates.com
paths:
  /v0.4/companies/search:
    get:
      operationId: ocSearchCompanies
      summary: Search companies by name.
      parameters:
        - in: query
          name: q
          required: true
          schema: { type: string }
        - in: query
          name: jurisdiction_code
          schema: { type: string, example: "us_de" }
        - in: query
          name: per_page
          schema: { type: integer, default: 25 }
        - in: query
          name: page
          schema: { type: integer, default: 1 }
      responses:
        "200":
          description: Search results.
